# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkorder.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from PyQt5 import QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import QApplication, QMainWindow, QHeaderView
import pymysql

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(931, 606)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(80, 130, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 310, 87, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(200, 80, 641, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 100, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 270, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(480, 50, 72, 15))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(740, 480, 111, 41))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 931, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "订单编号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "档口编号"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "订单时间"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "菜品编号"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "评价编号"))
        self.label.setText(_translate("MainWindow", "选择食堂"))
        self.label_2.setText(_translate("MainWindow", "选择档口"))
        self.label_3.setText(_translate("MainWindow", "历史订单"))
        self.pushButton.setText(_translate("MainWindow", "读取订单"))

class MyMainWindow_8(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(MyMainWindow_8,self).__init__()
        self.setupUi(self)

        self.pushButton.clicked.connect(self.pushB_read_Clicked)
    def pushB_read_Clicked(self):
        print("1")
        conn = pymysql.connect(host='localhost', port=3306, user='root', password="123456", db="canteen")
        cur = conn.cursor()

        store_id1 = self.comboBox_2.currentText()
        print(store_id1)
        # 查询的sql语句
        sql = "SELECT order_id, store_id, order_time,food_id,comment_id  FROM canteen.order WHERE store_id="+store_id1
        cur.execute(sql)
        # 获取查询到的数据，是以字典的形式存储的，所以读取需要使用data[i][j]下标定位
        data = cur.fetchall()
        # 打印测试
        print(data)
        # print(data[0][0])
        # 将id和name显示到界面表格上
        self.tableWidget.setItem(0, 0, QtWidgets.QTableWidgetItem(str(data[0][0])))
        self.tableWidget.setItem(0, 1, QtWidgets.QTableWidgetItem(str(data[0][1])))
        self.tableWidget.setItem(0, 2, QtWidgets.QTableWidgetItem(str(data[0][2])))
        self.tableWidget.setItem(0, 3, QtWidgets.QTableWidgetItem(str(data[0][3])))
        self.tableWidget.setItem(0, 4, QtWidgets.QTableWidgetItem(str(data[0][4])))
        if (len(data))>1:
         self.tableWidget.setItem(1, 0, QtWidgets.QTableWidgetItem(str(data[1][0])))
         self.tableWidget.setItem(1, 1, QtWidgets.QTableWidgetItem(str(data[1][1])))
         self.tableWidget.setItem(1, 2, QtWidgets.QTableWidgetItem(str(data[1][2])))
         self.tableWidget.setItem(1, 3, QtWidgets.QTableWidgetItem(str(data[1][3])))
         self.tableWidget.setItem(1, 4, QtWidgets.QTableWidgetItem(str(data[1][4])))
        if (len(data)) > 2:
            self.tableWidget.setItem(2, 0, QtWidgets.QTableWidgetItem(str(data[2][0])))
            self.tableWidget.setItem(2, 1, QtWidgets.QTableWidgetItem(str(data[2][1])))
            self.tableWidget.setItem(2, 2, QtWidgets.QTableWidgetItem(str(data[2][2])))
            self.tableWidget.setItem(2, 3, QtWidgets.QTableWidgetItem(str(data[2][3])))
            self.tableWidget.setItem(2, 4, QtWidgets.QTableWidgetItem(str(data[2][4])))
        if (len(data)) > 3:
            self.tableWidget.setItem(3, 0, QtWidgets.QTableWidgetItem(str(data[3][0])))
            self.tableWidget.setItem(3, 1, QtWidgets.QTableWidgetItem(str(data[3][1])))
            self.tableWidget.setItem(3, 2, QtWidgets.QTableWidgetItem(str(data[3][2])))
            self.tableWidget.setItem(3, 3, QtWidgets.QTableWidgetItem(str(data[3][3])))
            self.tableWidget.setItem(3, 4, QtWidgets.QTableWidgetItem(str(data[3][4])))
        if (len(data)) > 4:
            self.tableWidget.setItem(4, 0, QtWidgets.QTableWidgetItem(str(data[4][0])))
            self.tableWidget.setItem(4, 1, QtWidgets.QTableWidgetItem(str(data[4][1])))
            self.tableWidget.setItem(4, 2, QtWidgets.QTableWidgetItem(str(data[4][2])))
            self.tableWidget.setItem(4, 3, QtWidgets.QTableWidgetItem(str(data[4][3])))
            self.tableWidget.setItem(4, 4, QtWidgets.QTableWidgetItem(str(data[4][4])))
        if (len(data)) > 5:
            self.tableWidget.setItem(5, 0, QtWidgets.QTableWidgetItem(str(data[5][0])))
            self.tableWidget.setItem(5, 1, QtWidgets.QTableWidgetItem(str(data[5][1])))
            self.tableWidget.setItem(5, 2, QtWidgets.QTableWidgetItem(str(data[5][2])))
            self.tableWidget.setItem(5, 3, QtWidgets.QTableWidgetItem(str(data[5][3])))
            self.tableWidget.setItem(5, 4, QtWidgets.QTableWidgetItem(str(data[5][4])))
        if (len(data)) > 6:
            self.tableWidget.setItem(6, 0, QtWidgets.QTableWidgetItem(str(data[6][0])))
            self.tableWidget.setItem(6, 1, QtWidgets.QTableWidgetItem(str(data[6][1])))
            self.tableWidget.setItem(6, 2, QtWidgets.QTableWidgetItem(str(data[6][2])))
            self.tableWidget.setItem(6, 3, QtWidgets.QTableWidgetItem(str(data[6][3])))
            self.tableWidget.setItem(6, 4, QtWidgets.QTableWidgetItem(str(data[6][4])))
        if (len(data)) > 7:
            self.tableWidget.setItem(7, 0, QtWidgets.QTableWidgetItem(str(data[7][0])))
            self.tableWidget.setItem(7, 1, QtWidgets.QTableWidgetItem(str(data[7][1])))
            self.tableWidget.setItem(7, 2, QtWidgets.QTableWidgetItem(str(data[7][2])))
            self.tableWidget.setItem(7, 3, QtWidgets.QTableWidgetItem(str(data[7][3])))
            self.tableWidget.setItem(7, 4, QtWidgets.QTableWidgetItem(str(data[7][4])))
        if (len(data)) > 8:
            self.tableWidget.setItem(8, 0, QtWidgets.QTableWidgetItem(str(data[8][0])))
            self.tableWidget.setItem(8, 1, QtWidgets.QTableWidgetItem(str(data[8][1])))
            self.tableWidget.setItem(8, 2, QtWidgets.QTableWidgetItem(str(data[8][2])))
            self.tableWidget.setItem(8, 3, QtWidgets.QTableWidgetItem(str(data[8][3])))
            self.tableWidget.setItem(8, 4, QtWidgets.QTableWidgetItem(str(data[8][4])))
        if (len(data)) > 9:
            self.tableWidget.setItem(9, 0, QtWidgets.QTableWidgetItem(str(data[9][0])))
            self.tableWidget.setItem(9, 1, QtWidgets.QTableWidgetItem(str(data[9][1])))
            self.tableWidget.setItem(9, 2, QtWidgets.QTableWidgetItem(str(data[9][2])))
            self.tableWidget.setItem(9, 3, QtWidgets.QTableWidgetItem(str(data[9][3])))
            self.tableWidget.setItem(9, 4, QtWidgets.QTableWidgetItem(str(data[9][4])))

        # if (self.tableWidget.setItem(1, 0, QtWidgets.QTableWidgetItem(str(data[1][0])))):
        #    self.tableWidget.setItem(1, 0, QtWidgets.QTableWidgetItem(str(data[1][0])))
        #    self.tableWidget.setItem(1, 1, QtWidgets.QTableWidgetItem(str(data[1][1])))
        #    self.tableWidget.setItem(1, 2, QtWidgets.QTableWidgetItem(str(data[1][2])))

        cur.close()
        conn.close()