# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import QApplication, QMainWindow, QHeaderView
import pymysql

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(919, 598)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(70, 110, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(360, 10, 131, 51))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(220, 100, 541, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 80, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(470, 80, 72, 15))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "1"))
        self.comboBox.setItemText(1, _translate("Form", "2"))
        self.comboBox.setItemText(2, _translate("Form", "3"))
        self.comboBox.setItemText(3, _translate("Form", "4"))
        self.comboBox.setItemText(4, _translate("Form", "5"))
        self.comboBox.setItemText(5, _translate("Form", "6"))
        self.comboBox.setItemText(6, _translate("Form", "7"))
        self.comboBox.setItemText(7, _translate("Form", "8"))
        self.comboBox.setItemText(8, _translate("Form", "9"))
        self.comboBox.setItemText(9, _translate("Form", "10"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-style:italic;\">学生菜单</span></p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "菜品名称"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "菜品编号"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "菜系"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "菜品价格"))
        self.label_2.setText(_translate("Form", "选择档口"))
        self.label_3.setText(_translate("Form", "菜单"))


class MyWidget_10(QtWidgets.QMainWindow,Ui_Form):
    def __init__(self):
        super(MyWidget_10, self).__init__()
        self.setupUi(self)

        store_id1 = self.comboBox.currentText()
        conn = pymysql.connect(host='localhost', port=3306, user='root', password="123456", db="canteen")
        cur = conn.cursor()
        print("1")
        # 查询的sql语句
        sql = "SELECT food_name,food_id,foodstyle_id,food_price FROM canteen.food ;"
        print(sql)
        cur.execute(sql)

        # 获取查询到的数据，是以字典的形式存储的，所以读取需要使用data[i][j]下标定位
        data = cur.fetchall()
        # 打印测试
        print(data)
        # print(data[0][0])
        # 将id和name显示到界面表格上
        self.tableWidget.setItem(0, 0, QtWidgets.QTableWidgetItem(str(data[0][0])))
        self.tableWidget.setItem(0, 1, QtWidgets.QTableWidgetItem(str(data[0][1])))
        self.tableWidget.setItem(0, 2, QtWidgets.QTableWidgetItem(str(data[0][2])))
        self.tableWidget.setItem(0, 2, QtWidgets.QTableWidgetItem(str(data[0][3])))
        if (len(data)) > 1:
            self.tableWidget.setItem(1, 0, QtWidgets.QTableWidgetItem(str(data[1][0])))
            self.tableWidget.setItem(1, 1, QtWidgets.QTableWidgetItem(str(data[1][1])))
            self.tableWidget.setItem(1, 2, QtWidgets.QTableWidgetItem(str(data[1][2])))
            self.tableWidget.setItem(1, 2, QtWidgets.QTableWidgetItem(str(data[1][3])))
        if (len(data)) > 2:
            self.tableWidget.setItem(2, 0, QtWidgets.QTableWidgetItem(str(data[2][0])))
            self.tableWidget.setItem(2, 1, QtWidgets.QTableWidgetItem(str(data[2][1])))
            self.tableWidget.setItem(2, 2, QtWidgets.QTableWidgetItem(str(data[2][2])))
            self.tableWidget.setItem(2, 2, QtWidgets.QTableWidgetItem(str(data[2][3])))
        if (len(data)) > 3:
            self.tableWidget.setItem(3, 0, QtWidgets.QTableWidgetItem(str(data[3][0])))
            self.tableWidget.setItem(3, 1, QtWidgets.QTableWidgetItem(str(data[3][1])))
            self.tableWidget.setItem(3, 2, QtWidgets.QTableWidgetItem(str(data[3][2])))
            self.tableWidget.setItem(3, 2, QtWidgets.QTableWidgetItem(str(data[3][3])))
        cur.close()
        conn.close()
