# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'placeorder.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time

import numpy
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

from PyQt5 import QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import QApplication, QMainWindow, QHeaderView
import pymysql
from menu import *
from pattern import MyWidget_11


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1399, 884)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 720, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 720, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(750, 720, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1160, 680, 111, 91))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(160, 100, 411, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(140, 580, 441, 91))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(640, 10, 104, 41))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(820, 250, 131, 121))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 60, 101, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 550, 81, 20))
        self.label_2.setObjectName("label_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1150, 250, 121, 111))
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1399, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "读取订单"))
        self.pushButton_2.setText(_translate("MainWindow", "加入菜品"))
        self.pushButton_3.setText(_translate("MainWindow", "删除菜品"))
        self.pushButton_4.setText(_translate("MainWindow", "完成订单"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "菜品编号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "档口编号"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "用户编号"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "选择"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "用户编号"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "档口编号"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "菜品编号"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">购物车</span></p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "菜品查询"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">当前订单</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">菜品操作</span></p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "菜品识别"))

data_1 = numpy.zeros((10,3),dtype=int)

class MyMainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(MyMainWindow, self).__init__()
        self.setupUi(self)
        # 表格扩充拉伸
        self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget_2.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)

        self.pushButton_3.clicked.connect(self.pushB_delete_Clicked)
        self.pushButton_2.clicked.connect(self.pushB_insert_Clicked)
        self.pushButton_4.clicked.connect(self.pushB_putorder_Clicked)
        # 【读取按钮】功能
        self.pushButton.clicked.connect(self.pushB_read_Clicked)
        self.pushButton_5.clicked.connect(self.pushB_search_Clicked)
        self.pushButton_6.clicked.connect(self.pushB_recognizition_Clicked)

    # 【读取内容】按钮功能
    def pushB_read_Clicked(self):
        global data_1
        #conn = pymysql.connect(host='localhost', port=3306, user='root', password="123456", db="canteen")
        #cur = conn.cursor()
        # 查询的sql语句
        #sql = "SELECT * FROM canteen.order;"
        #cur.execute(sql)
        # 获取查询到的数据，是以字典的形式存储的，所以读取需要使用data[i][j]下标定位
        #data = cur.fetchall()
        #data_1 = numpy.zeros((10,3))
        # 打印测试

        #print(data[0][0])
        # 将id和name显示到界面表格上
        self.tableWidget.setItem(0, 0, QtWidgets.QTableWidgetItem(str(data_1[0][0])))
        self.tableWidget.setItem(0, 1, QtWidgets.QTableWidgetItem(str(data_1[0][1])))
        self.tableWidget.setItem(0, 2, QtWidgets.QTableWidgetItem(str(data_1[0][2])))
        self.tableWidget.setItem(1, 0, QtWidgets.QTableWidgetItem(str(data_1[1][0])))
        self.tableWidget.setItem(1, 1, QtWidgets.QTableWidgetItem(str(data_1[1][1])))
        self.tableWidget.setItem(1, 2, QtWidgets.QTableWidgetItem(str(data_1[1][2])))
        self.tableWidget.setItem(2, 0, QtWidgets.QTableWidgetItem(str(data_1[2][0])))
        self.tableWidget.setItem(2, 1, QtWidgets.QTableWidgetItem(str(data_1[2][1])))
        self.tableWidget.setItem(2, 2, QtWidgets.QTableWidgetItem(str(data_1[2][2])))
        self.tableWidget.setItem(3, 0, QtWidgets.QTableWidgetItem(str(data_1[3][0])))
        self.tableWidget.setItem(3, 1, QtWidgets.QTableWidgetItem(str(data_1[3][1])))
        self.tableWidget.setItem(3, 2, QtWidgets.QTableWidgetItem(str(data_1[3][2])))
        self.tableWidget.setItem(4, 0, QtWidgets.QTableWidgetItem(str(data_1[4][0])))
        self.tableWidget.setItem(4, 1, QtWidgets.QTableWidgetItem(str(data_1[4][1])))
        self.tableWidget.setItem(4, 2, QtWidgets.QTableWidgetItem(str(data_1[4][2])))
        self.tableWidget.setItem(5, 0, QtWidgets.QTableWidgetItem(str(data_1[5][0])))
        self.tableWidget.setItem(5, 1, QtWidgets.QTableWidgetItem(str(data_1[5][1])))
        self.tableWidget.setItem(5, 2, QtWidgets.QTableWidgetItem(str(data_1[5][2])))
        self.tableWidget.setItem(6, 0, QtWidgets.QTableWidgetItem(str(data_1[6][0])))
        self.tableWidget.setItem(6, 1, QtWidgets.QTableWidgetItem(str(data_1[6][1])))
        self.tableWidget.setItem(6, 2, QtWidgets.QTableWidgetItem(str(data_1[6][2])))
        self.tableWidget.setItem(7, 0, QtWidgets.QTableWidgetItem(str(data_1[7][0])))
        self.tableWidget.setItem(7, 1, QtWidgets.QTableWidgetItem(str(data_1[7][1])))
        self.tableWidget.setItem(7, 2, QtWidgets.QTableWidgetItem(str(data_1[7][2])))
        self.tableWidget.setItem(8, 0, QtWidgets.QTableWidgetItem(str(data_1[8][0])))
        self.tableWidget.setItem(8, 1, QtWidgets.QTableWidgetItem(str(data_1[8][1])))
        self.tableWidget.setItem(8, 2, QtWidgets.QTableWidgetItem(str(data_1[8][2])))
        self.tableWidget.setItem(9, 0, QtWidgets.QTableWidgetItem(str(data_1[9][0])))
        self.tableWidget.setItem(9, 1, QtWidgets.QTableWidgetItem(str(data_1[9][1])))
        self.tableWidget.setItem(9, 2, QtWidgets.QTableWidgetItem(str(data_1[9][2])))
        #cur.close()
        #conn.close()

        # 【插入数据】按钮

    # 【插入数据】按钮功能
    def pushB_insert_Clicked(self):
        global data_1
        #conn = pymysql.connect(host='localhost', port=3306, user='root', password="123456", db="canteen")
        #cur = conn.cursor()
        # 先读取右边表格输入的ID和姓名
        user_id1 = self.tableWidget_2.item(0, 0).text()
        store_id1= self.tableWidget_2.item(0, 1).text()
        food_id1= self.tableWidget_2.item(0, 2).text()
        for i in range(10):
            if (data_1[i][0]== 0):
             data_1[i][0] = food_id1
             data_1[i][1] = store_id1
             data_1[i][2] = user_id1
             break

        # 插入的sql语句
        #sql1 = "INSERT INTO canteen.order (order_id, user_id, store_id, order_time, food_id, comment_id) VALUES ("+order_id1+","+user_id1+","+store_id1+","+"+order_time1+"+","+food_id1+","+comment_id1+")"
        #sql1="INSERT INTO canteen.order (order_id, user_id, store_id, order_time, food_id, comment_id) VALUES (5,1,1,NOW(),1,1)"
        # 打印测试
        #print(sql1)


        # 执行sql语句，并发送给数据库
        #cur.execute(sql1)

        #conn.commit()
        #cur.close()
        #conn.close()

        # 【删除数据】按钮

    # 【删除数据】按钮功能
    def pushB_putorder_Clicked(self):
        global data_1
        # conn = pymysql.connect(host='localhost', port=3306, user='root', password="123456", db="canteen")
        # cur = conn.cursor()
        # 先读取右边表格输入的ID和姓名

    conn = pymysql.connect(host='localhost', port=3306, user='root', password="123456", db="canteen")
    cur = conn.cursor()

    # 先读取右边表格输入的ID和姓名

    order_id1 = '9';
    user_id1 = '1';
    store_id1 = '1';
    order_time1 = '0';
    food_id1 = '3';
    comment_id1 = '1';

    print("3")

    # 插入的sql语句
    sql1 = "INSERT INTO canteen.order (order_id, user_id, store_id, order_time, food_id, comment_id) VALUES (" + order_id1 + "," + user_id1 + "," + store_id1 + "," "NOW()" ","  + food_id1 + ","  + comment_id1 + ")";
    # 打印测试
    print(sql1)

    # 执行sql语句，并发送给数据库
    cur.execute(sql1)

    conn.commit()
    cur.close()
    conn.close()

    def pushB_recognizition_Clicked(self):
        self.the_window_11 = MyWidget_11()
        self.the_window_11.show()


    def pushB_search_Clicked(self):
        self.the_window_10 = MyWidget_10()
        self.the_window_10.show()

    def pushB_delete_Clicked(self):
        conn = pymysql.connect(host='localhost', port=3306, user='root', password="123456", db="canteen")
        cur = conn.cursor()
        # 先读取右边表格输入的ID
        customer_id1 = self.tableWidget_2.item(0, 0).text()
        # 删除的sql语句
        sql = "DELETE FROM canteen.order WHERE customer_id=" + customer_id1
        # 打印测试
        print(sql)
        # 执行sql语句，并发送给数据库
        cur.execute(sql)
        conn.commit()
        cur.close()
        conn.close()