# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from student import *
from untitled import  *
from staff import MyWidget_2
import sys

class Ui_MainWindow_1(object):
    def setupUi(self, MainWindow_1):
        MainWindow_1.setObjectName("MainWindow_1")
        MainWindow_1.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow_1)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 270, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 270, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow_1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow_1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_1)
        self.statusbar.setObjectName("statusbar")
        MainWindow_1.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_1)

    def retranslateUi(self, MainWindow_1):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_1.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "学生"))
        self.pushButton_2.setText(_translate("MainWindow_1", "职工"))

class MyMainWindow_1(QMainWindow, Ui_MainWindow_1):
    def __init__(self):
        super(MyMainWindow_1,self).__init__()
        self.setupUi(self)

        self.pushButton.clicked.connect(self.pushB_student_Clicked)
    def pushB_student_Clicked(self):
       self.the_window = MyWidget_1()
       self.the_window.show()

       self.pushButton_2.clicked.connect(self.pushB_staff_Clicked)
    def pushB_staff_Clicked(self):
       self.the_window_2 = MyWidget_2()
       self.the_window_2.show()