# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'staff_management.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

from PyQt5 import QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import QApplication, QMainWindow, QHeaderView
import pymysql


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1631, 1069)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(760, 540, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 780, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(750, 780, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1030, 780, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(610, 150, 391, 351))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(460, 660, 671, 71))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(720, 50, 181, 51))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1631, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "读取员工信息"))
        self.pushButton_2.setText(_translate("MainWindow", "增加员工"))
        self.pushButton_3.setText(_translate("MainWindow", "更新员工"))
        self.pushButton_4.setText(_translate("MainWindow", "删除员工"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "员工编号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "员工姓名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "所属档口"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "选择"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "员工编号"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "所属商户"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "员工姓名"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "员工年龄"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "所属档口"))
        self.textEdit.setHtml(_translate("MainWindow",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                         "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">员工管理</span></p></body></html>"))


class MyMainWindow_9(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(MyMainWindow_9, self).__init__()
        self.setupUi(self)
        # 表格扩充拉伸
        self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget_2.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)

        self.pushButton_3.clicked.connect(self.pushB_update_Clicked)
        self.pushButton_2.clicked.connect(self.pushB_insert_Clicked)
        self.pushButton_4.clicked.connect(self.pushB_delete_Clicked)
        # 【读取按钮】功能
        self.pushButton.clicked.connect(self.pushB_read_Clicked)

    # 【读取内容】按钮功能
    def pushB_read_Clicked(self):
        print("1")
        conn = pymysql.connect(host='localhost', port=3306, user='root', password="123456", db="canteen")
        cur = conn.cursor()
        # 查询的sql语句
        sql = "SELECT staff_id, staff_name, store_id  FROM canteen.staff;"
        cur.execute(sql)
        # 获取查询到的数据，是以字典的形式存储的，所以读取需要使用data[i][j]下标定位
        data = cur.fetchall()
        # 打印测试
        print(data)
        # print(data[0][0])
        # 将id和name显示到界面表格上
        self.tableWidget.setItem(0, 0, QtWidgets.QTableWidgetItem(str(data[0][0])))
        self.tableWidget.setItem(0, 1, QtWidgets.QTableWidgetItem(str(data[0][1])))
        self.tableWidget.setItem(0, 2, QtWidgets.QTableWidgetItem(str(data[0][2])))
       # if (self.tableWidget.setItem(1, 0, QtWidgets.QTableWidgetItem(str(data[1][0])))):
        #    self.tableWidget.setItem(1, 0, QtWidgets.QTableWidgetItem(str(data[1][0])))
        #    self.tableWidget.setItem(1, 1, QtWidgets.QTableWidgetItem(str(data[1][1])))
        #    self.tableWidget.setItem(1, 2, QtWidgets.QTableWidgetItem(str(data[1][2])))

        cur.close()
        conn.close()

    # 【更新数据】按钮

    # 【更新数据】按钮功能
    def pushB_update_Clicked(self):
        conn = pymysql.connect(host='localhost', port=3306, user='root', password="123456", db="canteen")
        cur = conn.cursor()
        # 先读取右边表格输入的ID和姓名
        staff_id1 = self.tableWidget_2.item(0, 0).text()
        sto_store_id1 = self.tableWidget_2.item(0, 1).text()
        staff_name1 = self.tableWidget_2.item(0, 2).text()
        staff_age1 = self.tableWidget_2.item(0, 3).text()
        store_id1 = self.tableWidget_2.item(0, 4).text()
        print("customer_id1")
        # 更新的sql语句
        sql = "UPDATE canteen.staff SET staff_id=" + staff_id1 + ",sto_store_id="+sto_store_id1+ ",staff_name=""\"" + staff_name1 + "\""+ ",staff_age="+staff_age1+ ",store_id="+store_id1+  " WHERE staff_id=" + staff_id1
        # 打印测试
        print(sql)
        # 执行sql语句，并发送给数据库
        cur.execute(sql)
        conn.commit()
        cur.close()
        conn.close()

        # 【插入数据】按钮

    # 【插入数据】按钮功能
    def pushB_insert_Clicked(self):
        conn = pymysql.connect(host='localhost', port=3306, user='root', password="123456", db="canteen")
        cur = conn.cursor()
        print("2")
        # 先读取右边表格输入的ID和姓名
        staff_id1 = self.tableWidget_2.item(0, 0).text()
        sto_store_id1 = self.tableWidget_2.item(0, 1).text()
        staff_name1 = self.tableWidget_2.item(0, 2).text()
        staff_age1 = self.tableWidget_2.item(0, 3).text()
        store_id1 = self.tableWidget_2.item(0, 4).text()

        # 插入的sql语句
        sql1 = "INSERT INTO canteen.staff (staff_id, sto_store_id, staff_name, staff_age, store_id) VALUES (" + staff_id1 + "," + sto_store_id1 + "," + "\"" + staff_name1 + "\"" + "," + str(staff_age1) + "," + store_id1 + ")"
        # 打印测试
        print(sql1)

        # 执行sql语句，并发送给数据库
        cur.execute(sql1)

        conn.commit()
        cur.close()
        conn.close()

        # 【删除数据】按钮

    # 【删除数据】按钮功能
    def pushB_delete_Clicked(self):
        conn = pymysql.connect(host='localhost', port=3306, user='root', password="123456", db="canteen")
        cur = conn.cursor()
        # 先读取右边表格输入的ID
        staff_id1 = self.tableWidget_2.item(0, 0).text()
        # 删除的sql语句
        sql = "DELETE FROM canteen.staff WHERE staff_id=" + staff_id1
        # 打印测试
        print(sql)
        # 执行sql语句，并发送给数据库
        cur.execute(sql)
        conn.commit()
        cur.close()
        conn.close()
