# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from orderhistory import *
from placeorder import  *

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(753, 474)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(160, 160, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 160, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "下单"))
        self.pushButton_2.setText(_translate("Form", "订单查询"))





class MyWidget_1(QtWidgets.QMainWindow,Ui_Form):
    def __init__(self):
        super(MyWidget_1, self).__init__()
        self.setupUi(self)

        self.pushButton.clicked.connect(self.pushB_placeorder_Clicked)
    def pushB_placeorder_Clicked(self):
        self.the_window_3 = MyMainWindow()
        self.the_window_3.show()

        self.pushButton_2.clicked.connect(self.pushB_orderhistory_Clicked)
    def pushB_orderhistory_Clicked(self):
        self.the_window_6 = MyMainWindow_6()
        self.the_window_6.show()